### ISSUE TITLE
Symfony rulesets are an anti-pattern

### ISSUE THREAD

**Issue by krukru** [BTCCTB/phpmd-rulesets#1]
One rule states that controller methods should end with suffix Action, but official Symfony docs state
```
Don't add the Action suffix to the methods of the controller actions.

The first Symfony versions required that controller method names ended in Action (e.g. newAction(), showAction()). This suffix became optional when annotations were introduced for controllers. In modern Symfony applications this suffix is neither required nor recommended, so you can safely remove it.
```

Another rule states that Entity objects should only contain getters and setters, calling anything else bad practice. In fact limiting your Entity objects to only getters and setters for the persistence layer is an Anemic Domain Model and goes against DDD and best practices.

You should either update the rules or put some disclaimer that they are outdated and subjective.

**Comment by damienlagae** [comment]
Thank you, but this project is no longer being maintained.
It was public for our external contributors and It is no longer used in our company.

In meantime, feel free to open a PR to fix this.

**Comment by krukru** [comment]
Cool! Thanks for the updated Readme :)
